%% This code can automatically cali camera, users should hold checkboards like dancing~
%%  It will output camera ins/ex values.

clear;
clc;

%   Call Kinect
vid = videoinput('kinect',1);

look = preview(vid);  
pause(3)

%%   Record Video

v = VideoWriter('dancing.avi');
v.FrameRate = 30;                    % FrameRate
open(v);

a='start recording, ready!' 
%figure;
for i = 1:100                         % 100 pictures in 10s
    frame = getsnapshot(vid);
    %imshow(frame);
    f.cdata = frame;
    f.colormap = [];
    writeVideo(v,f);
end
close(v);
a='finish recording'        % Video recording finish

%%   Read Video and Extract Frames

readvid = VideoReader ('dancing.avi');
nFrames = readvid.NumberOfFrames;


for j=1:20
    k=round((90-15).*rand(1,1)+15);             % gengerate a random number bet 15-100 (range 1-100)
    capture = read(readvid,k);                  % snapshot
    filename=['image_',num2str(j),'.bmp'];      % save image files
    imwrite(capture,filename,'bmp');
end
        
        
%%  Calibration

% Auto-generated by cameraCalibrator app on 02-Oct-2016
%-------------------------------------------------------

%% image file path should change to your pathway!!
% Define images to process
imageFileNames = {'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_1.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_2.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_3.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_4.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_5.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_6.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_7.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_8.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_9.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_10.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_11.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_12.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_13.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_14.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_15.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_16.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_17.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_18.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_19.bmp',...
    'C:\Users\Wenbin Dong\Desktop\METR7202\Lab2\video\image_20.bmp',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 24;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams, 'BarGraph');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{1});
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')


%%  Output calibration parameters
Intrinsic_Parameter = transpose(cameraParams.IntrinsicMatrix)
intrinsics.fc = cameraParams.FocalLength
intrinsics.alphac = cameraParams.Skew
%intrinsics.err
Principal_Point = cameraParams.PrincipalPoint
